import "./reset.css";
import "./globals.css";
import React from "react";
import type { Metadata } from "next";
import ClientComponent from "./ClientComponent";
import Cursor from "../components/Cursor/Cursor";

export const metadata: Metadata = {
  title: "akkiv-site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="ru">
      <ClientComponent />
      <body>
        {children}
        <Cursor />
      </body>
    </html>
  );
}
